### ISSUE TITLE
TypeError: code() takes at least 14 arguments (13 given)

### ISSUE THREAD

**Issue by a1eaiactaest** [a1eaiactaest/KoksSzachy#13]
Taki error gdy odpalamy KoksSzachy poprzez `./play.py` w trybie debugu.
```shell
Traceback (most recent call last):
  File "./play.py", line 9, in <module>
    app = Flask(__name__) 
  File "/home/prybiec/.local/lib/python3.8/site-packages/flask/app.py", line 601, in __init__
    self.add_url_rule(
  File "/home/prybiec/.local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/prybiec/.local/lib/python3.8/site-packages/flask/app.py", line 1278, in add_url_rule
    self.url_map.add(rule)
  File "/home/prybiec/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1563, in add
    rule.bind(self)
  File "/home/prybiec/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 710, in bind
    self.compile()
  File "/home/prybiec/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 766, in compile
    self._build = self._compile_builder(False)
  File "/home/prybiec/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1129, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/home/prybiec/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 1120, in compile
    co = types.CodeType(*code_args)
TypeError: code() takes at least 14 arguments (13 given)
```

**Comment by a1eaiactaest** [comment]
Odinstalowanie i zainstalowanie z powrotem `werkzeug` załatwiło u mnie sprawę.
```shell
$ pip3 uninstall werkzeug
# ...
$ pip3 install werkzeug
```
